librarysystem: patron.o book.o loan.o loans.o patrons.o books.o main.o
	g++ -o librarysystem patron.o patrons.o book.o books.o loan.o loans.o main.o

main.o: main.cpp book.h loan.h patron.h loans.h books.h patrons.h
	g++ -c main.cpp

book.o: book.cpp book.h 
	g++ -c book.cpp

patron.o: patron.cpp patron.h
	g++ -c patron.cpp

loan.o: loan.cpp loan.h
	g++ -c loan.cpp

books.o: books.cpp book.h books.h
	g++ -c books.cpp

loans.o: loans.cpp loan.h loans.h 
	g++ -c loans.cpp

patrons.o: patrons.cpp patron.h patrons.h
	g++ -c patrons.cpp
